# Site settings
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://motaquillahmaddane.com" # the base hostname & protocol for your site

title: Motaquillah Maddane
description: Personal Website

# Build settings
markdown: kramdown
highlighter: null

# Handling Reading
exclude: ["README.md", "LICENSE"]

# User's info
fullname: Motaquillah Maddane
